// <auto-generated />
namespace UniversityIot.UsersDataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Addedconstraints : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addedconstraints));
        
        string IMigrationMetadata.Id
        {
            get { return "201612172239254_Added constraints"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
