// <auto-generated />
namespace PolTrain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class TicketsandReservations : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TicketsandReservations));
        
        string IMigrationMetadata.Id
        {
            get { return "201701222035081_Tickets and Reservations"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
